version: '3'

services:
  TasksDB:
    image: mysql:latest
    container_name: TaskMicroService
    env_file:
      - ./Homework_09_tasks.env
    ports:
      - "3308:3306"
    volumes:
      - ./database:/var/lib/mysql

