version: '3'

services:
  UsersDB:
    image: mysql:latest
    container_name: UserMicroService
    env_file:
      - ./Homework_09_users.env
    ports:
      - "3307:3306"
    volumes:
      - ./database:/var/lib/mysql
