server:
  port: 8762
spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8080
          #uri: http://ums:8080
          predicates:
           - Path=/api/users/**
        - id: task_service
          uri: http://localhost:8081
          #uri: http://tms:8081
          predicates:
            - Path=/api/tasks/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka:8761/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

logging:
  level:
    root: INFO
    ru.ru.yampolskiy: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: ApiGateway.log