server:
  port: 8762
spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8080
          predicates:
           - Path=/api/users/**
        - id: task_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/tasks/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health