server:
  port: 8081
spring:
  application:
    name: tasks
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3308/TaskService
    #url: jdbc:mysql://tasksdb:3306/TaskService
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: User
    password: Password


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka:8761/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

logging:
  level:
    root: INFO
    ru.ru.yampolskiy: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: TaskMicroservice.log